---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      namespace: monitoring
    spec:
      containers:
      - name: myapp
        image: maltsevvm/nginx-static-app:latest
        ports:
          - containerPort: 80
            name: http

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: monitoring
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
